CREATE SEQUENCE geo_city_seq
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE geo_province (
    code VARCHAR(64)  NOT NULL,
    name VARCHAR(128) NOT NULL,
    CONSTRAINT pk_geo_province PRIMARY KEY (code)
);

CREATE TABLE geo_city (
    id            BIGINT       NOT NULL DEFAULT nextval('geo_city_seq'),
    province_code VARCHAR(64)  NOT NULL,
    name          VARCHAR(128) NOT NULL,
    CONSTRAINT pk_geo_city PRIMARY KEY (id),
    CONSTRAINT fk_geo_city_province FOREIGN KEY (province_code) REFERENCES geo_province (code),
    CONSTRAINT uk_geo_city_province_name UNIQUE (province_code, name)
);

CREATE INDEX idx_geo_city_province ON geo_city (province_code);

INSERT INTO geo_province (code, name) VALUES
    ('TEHRAN', 'تهران'),
    ('ALBORZ', 'البرز'),
    ('ISFAHAN', 'اصفهان'),
    ('FARS', 'فارس'),
    ('KHORASAN_RAZAVI', 'خراسان رضوی'),
    ('AZARBAIJAN_EAST', 'آذربایجان شرقی'),
    ('AZARBAIJAN_WEST', 'آذربایجان غربی'),
    ('GILAN', 'گیلان'),
    ('MAZANDARAN', 'مازندران'),
    ('KHUZESTAN', 'خوزستان'),
    ('QOM', 'قم'),
    ('QAZVIN', 'قزوین'),
    ('MARKAZI', 'مرکزی'),
    ('HAMADAN', 'همدان'),
    ('KERMAN', 'کرمان'),
    ('YAZD', 'یزد'),
    ('SEMNAN', 'سمنان'),
    ('ZANJAN', 'زنجان'),
    ('ARDABIL', 'اردبیل'),
    ('GOLESTAN', 'گلستان'),
    ('BUSHEHR', 'بوشهر'),
    ('HORMOZGAN', 'هرمزگان'),
    ('KERMANSHAH', 'کرمانشاه'),
    ('KORDESTAN', 'کردستان'),
    ('LORESTAN', 'لرستان'),
    ('ILAM', 'ایلام'),
    ('CHAHARMAHAL_AND_BAKHTIARI', 'چهارمحال و بختیاری'),
    ('KOHGILUYEH_AND_BOYER_AHMAD', 'کهگیلویه و بویراحمد'),
    ('KHORASAN_NORTH', 'خراسان شمالی'),
    ('KHORASAN_SOUTH', 'خراسان جنوبی'),
    ('SISTAN_AND_BALUCHESTAN', 'سیستان و بلوچستان');

INSERT INTO geo_city (id, province_code, name) VALUES
    (1,  'TEHRAN', 'تهران'),
    (2,  'TEHRAN', 'اسلامشهر'),
    (3,  'TEHRAN', 'شهریار'),
    (4,  'TEHRAN', 'ری'),
    (5,  'TEHRAN', 'قدس'),
    (6,  'TEHRAN', 'ملارد'),
    (7,  'TEHRAN', 'پاکدشت'),
    (8,  'TEHRAN', 'ورامین'),
    (9,  'TEHRAN', 'پردیس'),
    (10, 'TEHRAN', 'دماوند'),
    (11, 'ALBORZ', 'کرج'),
    (12, 'ALBORZ', 'فردیس'),
    (13, 'ALBORZ', 'نظرآباد'),
    (14, 'ALBORZ', 'هشتگرد'),
    (15, 'ALBORZ', 'اشتهارد'),
    (16, 'ISFAHAN', 'اصفهان'),
    (17, 'ISFAHAN', 'کاشان'),
    (18, 'ISFAHAN', 'نجف‌آباد'),
    (19, 'ISFAHAN', 'خمینی‌شهر'),
    (20, 'ISFAHAN', 'شاهین‌شهر'),
    (21, 'ISFAHAN', 'شهرضا'),
    (22, 'FARS', 'شیراز'),
    (23, 'FARS', 'مرودشت'),
    (24, 'FARS', 'جهرم'),
    (25, 'FARS', 'فسا'),
    (26, 'FARS', 'کازرون'),
    (27, 'FARS', 'لار'),
    (28, 'KHORASAN_RAZAVI', 'مشهد'),
    (29, 'KHORASAN_RAZAVI', 'نیشابور'),
    (30, 'KHORASAN_RAZAVI', 'سبزوار'),
    (31, 'KHORASAN_RAZAVI', 'تربت حیدریه'),
    (32, 'KHORASAN_RAZAVI', 'قوچان'),
    (33, 'AZARBAIJAN_EAST', 'تبریز'),
    (34, 'AZARBAIJAN_EAST', 'مراغه'),
    (35, 'AZARBAIJAN_EAST', 'مرند'),
    (36, 'AZARBAIJAN_EAST', 'اهر'),
    (37, 'AZARBAIJAN_EAST', 'میانه'),
    (38, 'AZARBAIJAN_WEST', 'ارومیه'),
    (39, 'AZARBAIJAN_WEST', 'خوی'),
    (40, 'AZARBAIJAN_WEST', 'مهاباد'),
    (41, 'AZARBAIJAN_WEST', 'بوکان'),
    (42, 'AZARBAIJAN_WEST', 'میاندوآب'),
    (43, 'GILAN', 'رشت'),
    (44, 'GILAN', 'بندر انزلی'),
    (45, 'GILAN', 'لاهیجان'),
    (46, 'GILAN', 'لنگرود'),
    (47, 'GILAN', 'آستارا'),
    (48, 'MAZANDARAN', 'ساری'),
    (49, 'MAZANDARAN', 'بابل'),
    (50, 'MAZANDARAN', 'آمل'),
    (51, 'MAZANDARAN', 'قائم‌شهر'),
    (52, 'MAZANDARAN', 'تنکابن'),
    (53, 'MAZANDARAN', 'چالوس'),
    (54, 'KHUZESTAN', 'اهواز'),
    (55, 'KHUZESTAN', 'آبادان'),
    (56, 'KHUZESTAN', 'خرمشهر'),
    (57, 'KHUZESTAN', 'دزفول'),
    (58, 'KHUZESTAN', 'اندیمشک'),
    (59, 'KHUZESTAN', 'ماهشهر'),
    (60, 'QOM', 'قم'),
    (61, 'QAZVIN', 'قزوین'),
    (62, 'QAZVIN', 'تاکستان'),
    (63, 'QAZVIN', 'آبیک'),
    (64, 'MARKAZI', 'اراک'),
    (65, 'MARKAZI', 'ساوه'),
    (66, 'MARKAZI', 'خمین'),
    (67, 'HAMADAN', 'همدان'),
    (68, 'HAMADAN', 'ملایر'),
    (69, 'HAMADAN', 'نهاوند'),
    (70, 'KERMAN', 'کرمان'),
    (71, 'KERMAN', 'سیرجان'),
    (72, 'KERMAN', 'رفسنجان'),
    (73, 'KERMAN', 'جیرفت'),
    (74, 'KERMAN', 'بم'),
    (75, 'YAZD', 'یزد'),
    (76, 'YAZD', 'میبد'),
    (77, 'YAZD', 'اردکان'),
    (78, 'SEMNAN', 'سمنان'),
    (79, 'SEMNAN', 'شاهرود'),
    (80, 'SEMNAN', 'دامغان'),
    (81, 'ZANJAN', 'زنجان'),
    (82, 'ZANJAN', 'ابهر'),
    (83, 'ARDABIL', 'اردبیل'),
    (84, 'ARDABIL', 'پارس‌آباد'),
    (85, 'ARDABIL', 'مشگین‌شهر'),
    (86, 'GOLESTAN', 'گرگان'),
    (87, 'GOLESTAN', 'گنبد کاووس'),
    (88, 'GOLESTAN', 'بندر ترکمن'),
    (89, 'BUSHEHR', 'بوشهر'),
    (90, 'BUSHEHR', 'برازجان'),
    (91, 'BUSHEHR', 'گناوه'),
    (92, 'HORMOZGAN', 'بندرعباس'),
    (93, 'HORMOZGAN', 'میناب'),
    (94, 'HORMOZGAN', 'قشم'),
    (95, 'HORMOZGAN', 'کیش'),
    (96, 'KERMANSHAH', 'کرمانشاه'),
    (97, 'KERMANSHAH', 'اسلام‌آباد غرب'),
    (98, 'KORDESTAN', 'سنندج'),
    (99, 'KORDESTAN', 'سقز'),
    (100, 'KORDESTAN', 'مریوان'),
    (101, 'LORESTAN', 'خرم‌آباد'),
    (102, 'LORESTAN', 'بروجرد'),
    (103, 'LORESTAN', 'دورود'),
    (104, 'ILAM', 'ایلام'),
    (105, 'ILAM', 'دهلران'),
    (106, 'CHAHARMAHAL_AND_BAKHTIARI', 'شهرکرد'),
    (107, 'CHAHARMAHAL_AND_BAKHTIARI', 'بروجن'),
    (108, 'KOHGILUYEH_AND_BOYER_AHMAD', 'یاسوج'),
    (109, 'KOHGILUYEH_AND_BOYER_AHMAD', 'دوگنبدان'),
    (110, 'KHORASAN_NORTH', 'بجنورد'),
    (111, 'KHORASAN_NORTH', 'شیروان'),
    (112, 'KHORASAN_SOUTH', 'بیرجند'),
    (113, 'KHORASAN_SOUTH', 'قائن'),
    (114, 'SISTAN_AND_BALUCHESTAN', 'زاهدان'),
    (115, 'SISTAN_AND_BALUCHESTAN', 'زابل'),
    (116, 'SISTAN_AND_BALUCHESTAN', 'چابهار'),
    (117, 'SISTAN_AND_BALUCHESTAN', 'ایرانشهر');

SELECT setval('geo_city_seq', 200);

