-- Payment / refund ledger rows for an order (Order 1 — N Transaction).
CREATE SEQUENCE ORDER_TRANSACTION_SEQ
    START WITH 1
    INCREMENT BY 50 NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE ORDER_TRANSACTION
(
    ID         BIGINT         NOT NULL DEFAULT NEXTVAL('order_transaction_seq'),
    ORDER_ID   BIGINT         NOT NULL,
    TYPE       VARCHAR(32)    NOT NULL,
    AMOUNT     NUMERIC(14, 2) NOT NULL,
    REFERENCE  VARCHAR(255)   NOT NULL,
    IBAN       VARCHAR(26),
    CREATED_AT TIMESTAMP      NOT NULL DEFAULT NOW(),

    CONSTRAINT PK_ORDER_TRANSACTION PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_TRANSACTION_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID) ON DELETE CASCADE
);

CREATE INDEX IDX_ORDER_TRANSACTION_ORDER ON ORDER_TRANSACTION (ORDER_ID);
